### ISSUE TITLE
MESSAGE: Adapter is not a constructor

### ISSUE THREAD

**Issue by shreegowtham27** [mainawycliffe/ghost-firebase-storage-adapter#1]
node -v
v14.15.3

Hai, I am getting this error on using this plugin.

I am in the latest version of Ghost.

Please find the software versions below.

**ENV**

node -v

v14.15.3

npm -v

6.14.10

ghost -v

Ghost-CLI version: 1.15.3
Ghost version: 3.40.2 

**config.production.json**

```
"storage": {
    "active": "firebase",
    "firebase": {
      "serviceAccount": "./service-ac.json",
      "bucketName": "<bucketName>",
      "basePath": "/<path>",
      "uploadOptions": {
        "gzip": true,
        "metadata": {
          "cacheControl": "public, max-age=31536000"
        }
      }
    }
  }
```

**Comment by shreegowtham27** [comment]
Additional Info :

Debug Information:
    OS: Ubuntu, v18.04.1 LTS
    Node Version: v14.15.3
    Ghost Version: 3.40.2
    Ghost-CLI Version: 1.15.3
    Environment: production
    Command: 'ghost doctor'

**Comment by shreegowtham27** [comment]
Whenever I run `ghost start`

This is the following message that I am getting 

                                                                                                                                            
Found a development config but not a production config, running in development mode instead
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Checking binary dependencies
✖ Starting Ghost: ghost-local
A GhostError occurred.

**Message: Adapter is not a constructor**

Debug Information:
    OS: Ubuntu, v20.04.1 LTS
    Node Version: v14.15.3
    Ghost Version: 3.40.2
    Ghost-CLI Version: 1.15.3
    Environment: development
    Command: 'ghost start'
    
**Ghost Log Info**

```
NAME: InternalServerError
MESSAGE: Adapter is not a constructor

level: normal

InternalServerError: Adapter is not a constructor
    at new GhostError (<Path to Ghost>/versions/3.40.2/node_modules/@tryghost/errors/lib/errors.js:10:26)
    at <Path to Ghost>/versions/3.40.2/core/index.js:16:23

TypeError: Adapter is not a constructor
    at AdapterManager.getAdapter (<Path to Ghost>/versions/3.40.2/node_modules/@tryghost/adapter-manager/lib/AdapterManager.js:115:25)
    at Object.getAdapter (<Path to Ghost>/versions/3.40.2/core/server/services/adapter-manager/index.js:26:31)
    at Object.getStorage (<Path to Ghost>/versions/3.40.2/core/server/adapters/storage/index.js:4:27)
    at setupSiteApp (<Path to Ghost>/versions/3.40.2/core/server/web/site/app.js:111:71)
    at setupParentApp (<Path to Ghost>/versions/3.40.2/core/server/web/parent/app.js:65:44)
    at <Path to Ghost>/versions/3.40.2/core/server/index.js:121:52
```

**Comment by davidstackio** [comment]
I'm also getting this issue with ghost 3.40.5.

**Comment by shreegowtham27** [comment]
> I'm also getting this issue with ghost 3.40.5.

I have moved to [gcs plugin](https://github.com/mikenikles/ghost-v3-google-cloud-storage), This also works similar to the firebase storage plugin. 

May be we can use this plugin until the plugin gets fixed.

**Comment by davidstackio** [comment]
@shreegowtham27 I was looking at that one too as an alternative. Good to know it works. Thanks.
